sseemayer/keepass-rs

src/decompress.rs, src/decrypt.rs, src/lib.rs, src/xmlparse.rs
This includes some minor readability fixes and removes a few needless `vec!`s and closures.
=> fix clippy warnings

src/keyfile.rs
Maybe this was leftover from debugging?
=> Removes a `println!` call from keyfile.rs

src/parse/kdb.rs, src/result.rs
* Remove unneeded formats, prefer .to_string()
* Remove redundant field name in struct
* Satisfied must_use by discarding other half of vec explicitly rather
than implicitly
=> Fix Clippy lints

Cargo.toml
Crates.io points to https://sseemayer.github.io/keepass-rs/ for documentation in the sidebar but link seems dead.
I think it's grabbing the info in Cargo.toml, so updating it.
=> Fix dead doc link

.github/workflows/rust-ci.yml, src/hmac_block_stream.rs, src/parse/kdbx4.rs, src/result.rs
This fixes #41 
Calculations were using `usize` and the values are >2^32 (apparently) -- a simple replace with u64 seems to work.
Added 1 test to CI on arm32 as it is _very_ slow right now. (I am investigating why)
=> Fix KDBX4 key calculation on 32 bit platforms

Cargo.lock, Cargo.toml, src/bin/kp-show-db.rs, src/crypt/ciphers.rs, src/crypt/mod.rs, src/result.rs
Could not update the AES dependency as it is affected by the deprecation of block-cipher, no easy replacement for ECB mode required for KDBX versions <4. Could have hacked it with a manual version but decided it was better to get the others up and running with the latest versions (which should bring some performance benefits on some platforms).
Results was changed due to unification of some results value upstream. Seems that there is less differentiation now on the key lengths etc. There is now a padding error that is returned, but should be careful about how that's exposed, as that way leads to oracle attacks if you're not careful. Not necessarily an issue for libraries but something to be born in mind for anything that uses this and returns data to users.
=> Updated dependecies and fixed issues related to them.

src/db.rs, src/parse/kdb.rs, src/parse/kdbx3.rs, src/xml_parse.rs, tests/entry_tests.rs
This PR implements UUID parsing for both entries and groups. Some of the code overlaps with [DavidVentura:recycle-uuid](https://github.com/sseemayer/keepass-rs/pull/43), but I tried to keep the implementations similar to minimize potential conflicts.
@sseemayer thanks for reviewing :eyes:
=> feat: parse group and entry uuids

README.md, src/lib.rs
This will populate the crate documentation page with everything in the README. It also avoids duplicating the same example in two places, and makes sure that the examples in the README are tested.
@sseemayer thanks for the review :pray:
=> docs: use readme for create doc

.github/workflows/rust-ci.yml
This moves the armv7 regression test to a separate job, so that failures in the regression tests are not confused with failures when running all the unit tests. The armv7 regression test was added today in https://github.com/sseemayer/keepass-rs/pull/45, and has been failing since. I tried fixing the test but was not able to so far, so I think splitting the test is a good compromise for now, so that we can rely on the unit tests again.
cc @DavidVentura 
I also removed reference to the `action-rs/cargo` action, because the rust toolchain is already installed by the `action-rs/toolchain` action. It's even recommended to do so by the action authors: https://github.com/actions-rs/cargo#use-cases
=> ci: isolate the armv7 regression test 

.github/workflows/rust-ci.yml
Fixes https://github.com/sseemayer/keepass-rs/issues/51 because the CI job will enforce the default `rustfmt` style.
=> ci: add a rustfmt linting job

src/db.rs, tests/file_read_tests.rs
This is a small refactoring to extract the `key_elements` generation function. It will be used elsewhere in the codebase when adding the KDBX4 support.
=> refactor: extract get_key_elements fns

Cargo.toml
This will make sure we avoid using the vulnerability described [here](https://rustsec.org/advisories/RUSTSEC-2020-0159.html)
The locked version is already 0.4.23, but consuming projects do not use the `Cargo.lock`
=> chore: avoid vulnerable chrono version

.github/workflows/rust-ci.yml
This will make sure that we don't run all the steps twice when working directly from the repo and not from a fork.
=> ci: do not run tests on every push

src/config.rs
These consts will be used when writing databases.
=> refactor: extract names for kdf variants

src/variant_dictionary.rs
Those same constants will be used when writing databases.
=> refactor: extract consts from variant dict parsing

Cargo.toml, src/keyfile.rs, src/xml_parse.rs
New version was published today, Some functions were marked as deprecated, so this PR will migrate to the newer form.
[Release notes are here](https://github.com/marshallpierce/rust-base64/commit/b59e4ea530bbcd030e0ddbda9cefc0ba8983a4f5)
=> chore: bump base64 to latest minor version

README.md
The build status badge was still redirecting to travis-ci, with the last build being 3 years old.
=> docs: update build status badge to gha

.github/workflows/merge.yml
This PR migrates the code coverage CI job from Travis to GitHub Actions. The code is based on [the tarpaulin documentation](https://github.com/xd009642/tarpaulin/tree/master/#github-actions). Since this is a public repository, we don't need to provide a token to codecov for the upload to work (see https://github.com/codecov/codecov-action#usage)
The workflow will only be triggered when merging to master.
=> ci: migrate code coverage to gha

.github/workflows/merge.yml
The current coverage workflow is failing with the latest tarpaulin image, as seen [here](https://github.com/sseemayer/keepass-rs/actions/runs/3912616535/jobs/6687480974).
This PR switches to the latest stable release instead. I tested locally, and I was able to generate the coverage report.
I think we'll also have to update the coverage badge in the README. The current codecov project page displays the following error message:
```
This repo has been deactivated 
```
=> fix: pin the tarpaulin image and use stable rust

.github/workflows/rust-ci.yml
The long form takes a lot of place in the README, so I suggest we use this well-known acronym instead.
=> ci: use acronym for ci job

src/db.rs, src/parse/kdbx4.rs, src/xml_parse.rs
`_database` is redundant in that case, and `::new` is already the name used by the `Group` and `Entry` structs.
=> refactor: rename database creation fn

src/db.rs, src/hmac_block_stream.rs, src/parse/kdbx4.rs, src/variant_dictionary.rs, tests/entry_tests.rs
Hi
Only adding a test because I don't understand what the problem is
When working on the TOTP PR, I noticed that providing a bad password gave:
```
fatal runtime error: stack overflow
```
I've isolated it to this `Error` type conversion, but the `#Error` macro is magic
=> fix: Prevent stack overflow due to circular type conversions of nested error types

codecov.yml
The codecov action started failing in the last commits, for example because the coverage decreased by -0.06%... I don't think this is productive, so I'm adding a threshold of 10% before considering that a merge failed the coverage test.
=> ci: add target and threshold for codecov

.github/workflows/commitlint.yml
The default help URL will be [this one](https://github.com/conventional-changelog/commitlint/#what-is-commitlint), but we can change it if we find it not helpful enough. For example, we could redirect to our own `CONTRIBUTING.md` once we have one.
This is required before we can add a workflow that automates the releases after a merge on master.
=> ci: add a workflow to lint commits

src/db.rs, src/parse/kdbx4.rs, src/xml_parse.rs
When I modified the database creation function to actually use the argon2 settings, I started seeing the following test errors:
```
thread 'xml_parse::xml_tests::test_entry' has overflowed its stack
```
Looks like there's a minimum memory required to derive the hashed password with argon2. I'm wondering if we should provide a default value, and a minimum value, to make sure that the value is large enough. I didn't see any recommendations on the crate's documentation.
=> feat: use argon2 kdf settings

.github/workflows/rust-ci.yml, src/bin/kp-show-otp.rs
This PR updates the `check` CI step to test all combinations of features. This should catch more bugs before they get merged into master, especially as we plan on adding more features to the crate. I also fixed a compilation error that made its way into master.
=> ci: cargo check all feature combinations

src/xml_db/parse/entry.rs, src/xml_db/parse/group.rs, src/xml_db/parse/meta.rs, src/xml_db/parse/mod.rs
Mostly to cover that the parsers fail in an expected way.
=> chore(xml): additional tests for parsing

src/db/mod.rs, src/parse/kdb.rs, src/parse/kdbx3.rs, src/parse/kdbx4.rs, src/parse/mod.rs
This PR centralizes all the code related to database version parsing and dumping, and eliminates duplicated database version parsing code. Some unused version related fields in the headers are also removed.
=> refactor: extract database version enum

Cargo.toml, src/bin/kp-get-version.rs, src/db/mod.rs, src/parse/mod.rs, tests/file_read_tests.rs
This can be useful for doing basic sanity checks on keepass database, to make sure that they have not been corrupted.
I think in the future we could merge some of the utilities into a single CLI binary, which would make it easier to discover the different features offered by the binaries in the crate.
=> feat: add a kp-get-version utility

src/db/entry.rs, src/db/group.rs, src/db/mod.rs, src/db/node.rs, src/parse/kdb.rs, src/parse/kdbx3.rs, src/xml_db/dump/entry.rs, src/xml_db/dump/group.rs, src/xml_db/mod.rs, src/xml_db/parse/entry.rs, src/xml_db/parse/group.rs
Now that we have a solid testing framework and the parsing and dumping infrastructure has matured, hammer out the final missing fields from the XML database
BREAKING CHANGE: Adds additional fields to Group and Entry
=> feat!: implement remaining XML fields

README.md
To make sure that there's no ambiguity about the project name, if accessed from the source code directly instead of github.
=> docs: use full project name in README

.github/workflows/merge.yml, .tarpaulin.toml
This job keeps failing as soon as the coverage drops even by a single line. I didn't find any tarpaulin or `codecov-action` option to disable that behavior, so I suggest we just ignore the failures for the moment. I'm also setting the `fail-under` option to make it explicit what our current coverage target is.
=> ci: prevent ci failure from coverage job

src/bin/kp-rewrite.rs, src/db/mod.rs
This commit extract a `generate_ivs` function so that we can generate new IVs both when creating a new database and when saving an existing database. The new unit test is a bit too weak, because we only test test `master_seed`, and because we don't validate that the IVs were regenerated *before* dumping the encrypted database. I'm not sure yet how we could improve that. I tried comparing the raw encrypted databases, but they already differ when using the `master` codebase, I'm guessing because of another source of randomness in the encryption process.
=> feat: regenerate the ivs on db save

.github/workflows/merge.yml, codecov.yml
I think I finally found out what the problem was. The `status` codecov job was configured, but we were not configuring the `patch` job, as documented [here](https://docs.codecov.com/docs/commit-status#patch-status). It should now only fail if the coverage goes below 80%, or if the coverage drops by more than 10% in a single commit.
I also removed the `fail_ci_if_error`. Excerpt from the [doc](https://github.com/codecov/codecov-action#arguments):
```
Specify if CI pipeline should fail when Codecov runs into errors during upload.
```
I think we want visibility on upload errors, so that we can troubleshoot what happened and fix the workflow.
=> ci: avoid codecov patch failures

src/db/mod.rs, src/format/mod.rs
I'm not sure where I took `3` from, but the minor value I'm getting when creating a database from KeePassXC is `0`. I also saw `4.1`, but I'm unable to recreate a database with that minor version. It might be related to the KDF or encryption schemes used.
=> fix: pin the minor kdbx4 version to 0

codecov.yml
The latest merges in `master` didn't fail, but I still think the patch behavior will cause problems in the future. The current `patch` config would fail if <80% of the **new** code is not covered. I think this is not useful because we already enforce a target for the overall codebase, and we will fail if the overall coverage drops by >10%.
There's a [`dry_run`](https://github.com/codecov/codecov-action#arguments) option in the codecov action that prevents the step from uploading the results. I think we could use that to also enforce the current coverage from within the PRs. This would allow us to enforce a certain coverage % before merging to master. We can wait until the library is more stable to enable that.
=> ci: disable target for differential coverage

src/bin/kp-dump-xml.rs, src/bin/kp-rewrite.rs, src/config.rs, src/db/mod.rs, src/format/kdb.rs, src/format/kdbx3.rs, src/format/kdbx4/dump.rs, src/format/kdbx4/mod.rs, src/format/kdbx4/parse.rs, src/format/mod.rs, src/xml_db/mod.rs
Instead of overwriting the various key seeds and IVs and testing that they were overwritten, only keep the buffers around during parsing and dynamically regenerate them during dumping.
BREAKING CHANGE: Database interface changed so that headers are not exposed directly anymore, but instead only DatabaseSettings are.
=> refactor!: never store keys or seeds

src/format/kdbx4/dump.rs, src/format/kdbx4/parse.rs, src/hmac_block_stream.rs
Extract another magic value that was duplicated between the parsing and dumping code into a constant.
=> refactor: extract hmac key end magic value

src/db/meta.rs, src/db/mod.rs, src/format/kdbx3.rs, src/format/kdbx4/dump.rs, src/format/kdbx4/mod.rs, src/format/kdbx4/parse.rs, src/xml_db/mod.rs
Closes #117
Since the fields for an attachment inside of a <Meta> tag and inside of a KDBX4 binary header are different, make the distinction explicit by splitting up the types
BREAKING CHANGE: New type for header_attachments field in Database
BREAKING CHANGE: Fewer members for BinaryAttachment parsed from XML
=> refactor!: split BinaryAttachment and HeaderAttachment

Cargo.toml, src/db/mod.rs, src/format/kdbx4/mod.rs, src/xml_db/mod.rs
Properly chain getrandom::Error and make Database::new infallible since no more random data needs to be generated
BREAKING CHANGE: Database::new returns Self instead of Result<Self>.
BREAKING CHANGE: DatabaseSaveError::Random contains the actual Error type inside it.
=> refactor!: clean up error types

.github/workflows/rust-ci.yml
This commit will cancel the CI workflow when additional changes are pushed to the PR.
=> ci: cancel in progress workflows on prs

src/db/mod.rs, src/format/kdb.rs, src/format/kdbx3.rs, src/format/kdbx4/parse.rs, src/xml_db/dump/meta.rs, src/xml_db/dump/mod.rs, src/xml_db/mod.rs, src/xml_db/parse/mod.rs
Closes #114
Parses and Dumps DeletedObject fields from the Root
BREAKING CHANGE: Adds new deleted_objects field to Database.
=> feat!: support DeletedObjects

Cargo.toml, src/db/entry.rs, src/db/group.rs, src/db/meta.rs, src/db/mod.rs, src/error.rs, src/xml_db/dump/mod.rs, src/xml_db/mod.rs, src/xml_db/parse/entry.rs, src/xml_db/parse/group.rs, src/xml_db/parse/meta.rs, src/xml_db/parse/mod.rs, tests/entry_tests.rs, tests/file_read_tests.rs
Closes #131
Instead of keeping the UUIDs of objects around as base64-encoded strings, actually parse them into Uuid objects. This also fixes some issues where UUID strings instead of base64-encoded UUIDs were serialized into the XML files.
BREAKING CHANGE: Changed type of UUID values from String to `uuid::Uuid`
=> feat!: parse base64-encoded UUID values

src/db/mod.rs
Some fields of the Meta struct were not having pub visibility.
=> feat: expose CustomIcons, Icon, MemoryProtection

README.md
We already have a badge that links to the documentation, so this header is superfluous.
=> docs: remove duplicate doc link

src/db/entry.rs, src/db/meta.rs, src/db/mod.rs, src/error.rs, src/xml_db/dump/mod.rs, src/xml_db/mod.rs, src/xml_db/parse/entry.rs, src/xml_db/parse/meta.rs, src/xml_db/parse/mod.rs
Instead of storing raw hex strings, create a Color struct and implement parsing and dumping for that.
BREAKING CHANGE: Color fields are not Strings, but Color values now.
=> feat!: parse colors

README.md
This will group the usage examples in the README and make them foldable, to make sure that the README is easier to scroll through. The result can be seen [here](https://github.com/sseemayer/keepass-rs/blob/db5837b957dc0d7e6305eb1a90b50d76f8c97802/README.md)
=> docs: group the usage examples

src/config.rs, src/error.rs, src/format/mod.rs
The DatabaseVersion should be part of the public interface since it is part of the DatabaseConfig
=> feat: expose DatabaseVersion

.github/workflows/ci.yml
Fixes https://github.com/sseemayer/keepass-rs/issues/119
This output seen in the PRs is not as explicit as the one we see on merges, but I didn't want to duplicate the `codedov.io` part of the workflow in multiple places. I think having the check is good enough, and we can always look at the details in case the job fails.
=> ci: run code coverage on prs

src/db/entry.rs, src/db/group.rs, src/db/mod.rs, src/xml_db/mod.rs
This PR implements the default time values that are stored in KDBX databases. I had to create a `now()` method because by default the `NaiveDateTime` will be created with the nanoseconds since the last leap second, which will not be preserved when dumping and parsing the database. This would result in the `test_entry` and `test_group` tests failing.
=> feat: implement default time values

src/db/entry.rs, src/db/group.rs
This PR adds an `Entry` function to commit changes to the history and to update the modification timestamp. This new function also encapsulates some expectations about the history, like the fact that recursive entry histories should not be allowed.
=> feat: support entry updates

src/db/entry.rs
BREAKING CHANGE: the `entries` field of the `History` struct is no longer accessible directly. The
`get_entries` function can instead be used to return a read-only reference to the entries. This is to
prevent the history entries from containing recursive history entries, which would prevent the database
from being opened by other applications like KeePassXC.
=> refactor: make history entries read-only

src/db/entry.rs
We have a dedicated function to create datetimes without the msecs, but we were not using it when updating the last modification time during the entry update.
=> fix: truncate msecs from update modification time

src/db/entry.rs, src/db/group.rs, src/db/mod.rs
Other KDBX parsers (like the one in KeePassXC)
store all the default times as fields of a class,
instead of items in a map. The result is that
default times that are not populated will be
given a default value at parsing time. This can
result in drift between an entry and its history items,
as described in https://github.com/sseemayer/keepass-rs/issues/153.
Populating all the default times is thus safer
for interoperability between KDBX4 parsers.
=> fix: set all default times when creating a node

.github/workflows/ci.yml, .github/workflows/merge.yml, README.md
The build status badge in the README was targeting the `ci` job, which is only running on pull requests. We used to run the `ci` workflow on the master branch, which is why the build status was marked as passing, but those workflow runs were 2 months old.
=> ci: use the master ci for build status badge

.github/workflows/ci.yml, Cargo.toml
The build for the docs was failing, as can be seen in the logs [here](https://docs.rs/crate/keepass/0.6.0/builds/770101). The issue was related to `rustfmt`, which is only a dev dependency, so I marked it as such. I think we were relying on `rustfmt` using the `derive` feature of serde, because the builds started failing after that. I enabled the `derive` feature explicitly to resolve the issue.
When this is merged, we will need to publish a new version in order to update the crates.io doc to the latest version.
=> ci: fix the docs build

src/db/mod.rs, src/xml_db/dump/mod.rs, src/xml_db/mod.rs, src/xml_db/parse/mod.rs
The CustomData in KeePassXC is handled as a hashmap, and it should processed in a similar way. Without the hashmap own iterators, setters and getters should be implemented instead of just using `.contains_key()` etc. directly. I was tempted to remove the `items` inside the `CustomData` so it could be just a define for the `HashMap<String, CustomDataItem>` but leaving as it is enabled some custom implementations for it in the future.
CustomData is now added to the Group too.
Downside of this change is that another struct is needed when parsing the data from XML because there the `<Item>` includes also the key. When dumping the data it has to make sure everything is put inside an `<Item>` again.
Some things I noticed while writing new tests. Should the parsing/dumping also handle situations …
=> fix: CustomData changes

Cargo.toml
This will fix the `out of date` warning currently displayed [on deps.rs](https://deps.rs/repo/github/sseemayer/keepass-rs)
=> feat(deps): bump hex-literal to 0.4.X

Cargo.toml
https://rustsec.org/advisories/RUSTSEC-2020-0071
Workarounds
A possible workaround for crates affected through the transitive dependency in chrono, is to avoid using the default oldtime feature dependency of the chrono crate by disabling its default-features and manually specifying the required features instead.
=> Update chrono dependency due to RUSTSEC-2020-0071

src/db/entry.rs
Previously, the last modification timestamp would
be updated only after committing a new entry history
item. This resulted in history entries with the
same last modification timestamp if an entry was
modified from two different places. While this is not
a problem now, it will be problematic when we
implement a merge/sync functionality.
This PR precedes https://github.com/sseemayer/keepass-rs/pull/155
=> fix: ensure unique modification timestamps for history entries

src/db/group.rs
Issue when using the "get" function to retrieve a group by its path.
Example PoC :
```
let path = Path::new("tests/resources/test_db_with_password.kdbx");
let mut db = Database::open(
&mut File::open(path).unwrap(),
DatabaseKey::with_password("demopass")
).unwrap();
if let Some(NodeRefMut::Group(e)) = db.root.get_mut(&["General"]) {
println!("Group: {}", e.name);
}
// This does not return a group !!!
if let Some(NodeRef::Group(e)) = db.root.get(&["General"]) {
println!("Group: {}", e.name);
}
```
=> fix: group's "get" function not returning groups

src/db/group.rs
This is a follow up on https://github.com/sseemayer/keepass-rs/pull/174
The function's documentation is also used to showcase how to use the library, so I don't want it to become to convoluted. Hence, I'm adding a unit test so we can easily add more tests in the future.
=> feat: add unit tests for Group::get

README.md, src/bin/kp-dump-json.rs, src/bin/kp-dump-xml.rs, src/bin/kp-rewrite.rs, src/bin/kp-show-db.rs, src/bin/kp-show-otp.rs, src/db/group.rs, src/db/mod.rs, src/db/otp.rs, src/format/kdbx4/mod.rs, src/key.rs, src/xml_db/mod.rs, tests/entry_tests.rs, tests/file_read_tests.rs
I think the memory occupied by this structure cannot be very large. For ease of use, it is a good idea to remove its lifetime annotation.
=> refactor(key)!: use a builder-like pattern and owned internal representation

README.md, src/db/group.rs, src/db/mod.rs, src/db/node.rs, src/format/kdb.rs, src/format/kdbx4/mod.rs, src/xml_db/mod.rs, src/xml_db/parse/group.rs
I also added an `add_child` function that calls `.into()` directly to reduce the verbosity of this common use-case.
This PR precedes https://github.com/sseemayer/keepass-rs/pull/155
=> feat: implement From trait for Node types

Cargo.toml
By default, `cargo publish` will include pretty much everything from the root directory in the published crate. We only really need the source code and the top-level documentation to be included in the crate.
=> chore: only include source files in published crate

Cargo.toml, src/crypt/kdf.rs
parallel execution was removed from the 2.0 version of rust-argon2, as seen in the releaes notes
https://github.com/sru-systems/rust-argon2/blob/master/CHANGELOG.md#200
=> build: bump argon2 version

src/db/mod.rs, src/format/kdb.rs, src/format/kdbx3.rs, src/format/kdbx4/dump.rs, src/format/kdbx4/mod.rs, src/format/kdbx4/parse.rs, src/key.rs, src/xml_db/mod.rs
This will make it easier to introduce challenge-response keys, since we can perform the challenge before the final call to `get_key_elements()`.
=> refactor: delay the generation of key elements

.github/workflows/merge.yml, Cargo.toml
This PR adds two steps to the on-merge workflow that will release a new Cargo version and push a new git tag on every new `master` commit. 
The `enable_prerelease_mode` option will make sure that version `1.0.0` is not published until we consider that the library's API is stable.
@sseemayer it looks like you were already pushing tags when publishing to Cargo so we won't have anything to do on that side before merging this PR. However, you will need to populate the repo's secrets with the `CARGO_REGISTRY_TOKEN`, since I am not an owner of that crate. The token only needs the `publish-update` scope, and I suggest that you scope the token so that it can only publish the `keepass` crate.
I've tested those two steps on a library that I maintain …
=> ci: automate the releases

Cargo.toml, src/bin/kp-purge-history.rs
Small utility that I needed to clean up the histories after developing the merge feature. I think it might also be useful to clean up a database that is getting too big.
=> feat: add a utility to purge the history items

Cargo.toml, src/bin/kp-dump-json.rs, src/bin/kp-dump-xml.rs, src/bin/kp-purge-history.rs, src/bin/kp-rewrite.rs, src/bin/kp-show-db.rs, src/bin/kp-show-otp.rs, src/key.rs
I also added a utility function to make sure that the password never leaves the DatabaseKey when using a password prompt. We might consider exposing this feature from the crate at some point, but for now the `utilities` feature has to be enabled.
I think this is only a partial solution and there are probably other features from the `secrecy` crate that we might want to add in the future.
Addresses https://github.com/sseemayer/keepass-rs/issues/171
=> feat: implement zeroize for DatabaseKey

src/db/group.rs, src/db/node.rs
This commit adds a few internal abstractions to make it easier to work with complex node paths. Using the UUID instead of the title or name is sometimes desirable because nothing guarantees that the entry titles or group names are unique. I also added a few `get` and `get_mut` tests to make sure there was no regression. The new types and functions are not public since I don't think they are stable just yet.
This is a prerequisite to https://github.com/sseemayer/keepass-rs/pull/155
=> feat: allow using the UUID to search for nodes

src/db/mod.rs, src/format/mod.rs
The unit tests could be a little more specific about the error type being raised, but I think testing that the function doesn't panic is good enough.
Fixes #191
=> fix: handle invalid version header size

.github/workflows/ci.yml, tests/file_read_tests.rs
This reference to `ChallengeResponseKey` was not fenced behind
a feature flag, which was preventing the tests from compiling.
I also added a CI check that would have caught the issue before merging (you can see that the CI job failed for the first commit). I'm not sure why it wasn't caught by `cargo hack` though. Ideally we would try building the crate with all feature combinations, including the tests. I'm not sure this is a viable long-term solution however since the number of features will probably continue growing.
=> fix: remove unfenced CRKey reference

src/format/kdbx4/parse.rs
The header_data variable is already defined in this function to validate the HMAC, and re-using it makes it easier to read the header checksum verification.
=> refactor: re-use header_data variable

.github/workflows/ci.yml, .github/workflows/merge.yml
This will get rid of all the warnings, as seen [here](https://github.com/sseemayer/keepass-rs/actions/runs/7155313481?pr=198) (now) compared to [here](https://github.com/sseemayer/keepass-rs/actions/runs/7149191407?pr=197) (before)
Fixes https://github.com/sseemayer/keepass-rs/issues/161
=> ci: migrate to dtolnay/rust-toolchain

rustfmt.toml, src/config.rs, src/crypt/ciphers.rs, src/crypt/mod.rs, src/db/entry.rs, src/db/mod.rs, src/db/otp.rs, src/error.rs, src/format/kdb.rs, src/format/kdbx3.rs, src/format/kdbx4/dump.rs, src/format/kdbx4/mod.rs, src/format/kdbx4/parse.rs, src/hmac_block_stream.rs, src/key.rs, src/variant_dictionary.rs, src/xml_db/dump/entry.rs, src/xml_db/dump/mod.rs, src/xml_db/mod.rs, src/xml_db/parse/entry.rs, src/xml_db/parse/group.rs, src/xml_db/parse/meta.rs, src/xml_db/parse/mod.rs, tests/entry_tests.rs, tests/file_read_tests.rs
I've been wanting to do that for a while. The default `max_width` for `rustfmt` is 100, which results in many split lines, given the verbosity of Rust. The PR should not be too difficult to review, but you don't have to trust me. You can copy the `rustfmt.toml` file and run the following script, and you should get to the same result:
```
#!/usr/bin/env bash
files=$(find . -name '*.rs')
IFS=$'\n'; for file in $files; do
rustfmt "$file"
done
```
=> chore: configure rustfmt

src/db/group.rs, src/db/node.rs
I initially wrote the `NodePathElement` abstraction to make it possible to use the `get` and `get_mut` functions with either titles or UUIDs. However, this abstraction makes it difficult to allow both owned strings and string references for the node path. This PR instead introduces a simpler `SearchField` enum, which is passed separately to the `get_internal` and `get_mut_internal` functions. This makes it possible to use `AsRef<str>` with the internal functions, thus allowing an owned path to be provided when searching for a node.
Note that I didn't migrate the `get` and `get_mut` functions to `AsRef<str>` yet, since this would be a breaking change. This can be done later in a separate commit, which should also include migration notes for users of the library. Using `AsRef<str>` is also …
=> refactor: allow owned path when searching for node

src/config.rs, src/db/mod.rs
I don't see a reason why Database could be not cloneable, since Entry, Group and even DatabaseKey already are.
=> feat: make Database cloneable

src/bin/kp-dump-json.rs, src/bin/kp-dump-xml.rs, src/bin/kp-purge-history.rs, src/bin/kp-rewrite.rs, src/bin/kp-show-db.rs, src/bin/kp-show-otp.rs, src/key.rs
This also fixes a bug with the `with_password_from_prompt` function that prevented users from entering an empty password.
BREAKING CHANGE: an empty password is no longer converted to a database key with no password when using the command-line utilities. The `--no-password` option has to be used to open a database without a password.
=> feat: add DatabaseKey::is_empty fn

.github/workflows/merge.yml
The last commit didn't trigger a new minor release as expected. I think it's because of how the regex is configured, since I've seen instances of a minor version being created when the breaking change description is at the beginning of the commit message.
BREAKING CHANGE: This commit trigger a minor release version which should have been generated for commit 229fe57c7d0fc50b8f9c3f6c4a117a245a1739eb
=> fix: trigger new minor version

Cargo.toml, src/bin/kp-yk-add.rs, src/bin/kp-yk-recover.rs, src/bin/kp-yk-remove.rs, src/key.rs, tests/file_read_tests.rs
This commit adds support for YubiKey challenge-response keys, and also adds a few utilities so that we can test the new feature. I only tested on Linux, but would be interested to know if it works on Mac and Windows. I also added a utility to recover a database by using the HMAC-SHA1 secret directly. This will allow us to deprecate the [`keepassxc-cr-recovery`](https://github.com/keepassxreboot/keepassxc/tree/develop/utils/keepassxc-cr-recovery) tool from keepassxc @droidmonkey 
The new unit test is ignored since a properly-configured yubikey is required for the test to pass.
Fixes #165
=> feat: add yubikey challenge-response

src/crypt/ciphers.rs
I tried searching for a reason why we would be using twofish padding for aes, but that change [dates all the way back to the initial PR ](https://github.com/sseemayer/keepass-rs/commit/3e8cad4b2bada7e43ca9955cdce9695b16087ecd#diff-286faac43a94819c5cf02776804fb5dc7a63bcddc8f2fb7c99d6346277856683R40), so I'm pretty sure it was just my mistake. I don't think this changes anything anyway since in the end they are both using `Pkcs7`, but I just feel like it's less confusing and more consistent with the decryption function to reference `Pkcs7` directly.
=> fix(aes): use consistent block padding

.github/workflows/merge.yml
This should fix the warning about node 16 being deprecated by GHA.
=> ci: bump semantic release action

src/hmac_block_stream.rs, tests/large_database_roundtrip_tests.rs
In this PR:
- Add test that writes and reads back a large database (100000). This exposes the issue with write corruption, which is not detected by other tests.
- Fix write corruption by removing chunking behavior. 
- The tests fail on master, but pass after the chunking is removed.
Closes #219
=> save_kdbx4: Fix write corruption for large Databases

.github/workflows/ci.yml, .github/workflows/merge.yml
Updates tarpaulin to 0.28.0 and the codecov-action to v4
Closes #222
=> chore: bump code coverage tool versions

Cargo.toml
I don't think it makes sense to pin the patch versions since this project is mainly used as a library.
=> feat: pin only major and minor versions

src/db/mod.rs
I don't think there's an issue with using `unwrap` here, since we have just created the timestamp so it must be valid.
=> chore: fix chrono deprecation warnings

src/xml_db/parse/group.rs
This PR adds a unit tests for empty group names, supported since https://github.com/sseemayer/keepass-rs/pull/234
=> chore: add unit test for empty group name

.github/workflows/ci.yml, commitlintrc.json
The 100 character limit in the commit body is very limiting, especially when we want to include URLs. This PR should make the situation slightly better, although I think in the future we should completely disable the line length check if a line is found to contain a URL. This would also allow us to preserve a smaller length limit for lines that do not container a URL.
=> chore: allow longer lines in commit messages

src/db/otp.rs
Both per:
- google authenticator: https://github.com/google/google-authenticator/wiki/Key-Uri-Format#issuer
- yubikey wiki: https://docs.yubico.com/yesdk/users-manual/application-oath/uri-string-format.html
`issuer` parameter in `otpauth://` URI scheme is optional
even though it's highly recommended to be present.
This parameter was actually optional in this repo initially 
(in https://github.com/sseemayer/keepass-rs/commit/0089160024add0b5e5a36af8f2373a63aa783e1e) 
but was changed to non optional. 
I'm changing it back to optional.
BREAKING CHANGE: makes `issuer` parameter Option instead of String
=> fix: make TOTP issuer field optional

Cargo.toml, src/db/entry.rs, src/db/group.rs, src/db/merge.rs, src/db/mod.rs
This is a re-implementation of the merge feature, which I initially attempted to implement in https://github.com/sseemayer/keepass-rs/pull/155
This new implementation is heavily inspired from the KeePassXC implementation.
I've been using this commit for over 6 months without any issues. I'd like to get the PR merged so that I don't have to rebase constantly, even though there are still some features missing. I prefixed the name of the cargo feature with an underscore so that it is hidden from docs.rs. I'll remove the underscore once we have feature parity with the KeePassXC implementation. The main merge feature missing is database metadata merging. I will add an issue to track this once this PR is merged.
Apart from the missing features, my main concern with the current implementation is …
=> feat: add merge feature

src/db/group.rs
lifetimes that were provided in the function parameters but not in the
return values led to errors while running cargo check. remove these
lifetimes since they can be elided automatically
=> fix(ci): remove superfluous lifetimes

src/xml_db/parse/meta.rs
fixes #246
The uuid crate has added an additional NonNilUuid type that implements
PartialEq<Uuid> [1], so we need to be specific about what type to
compare against.
[1] https://github.com/uuid-rs/uuid/commit/f570b5714c6e25546022e2afe25288492cfecf39
=> fix(test): explicit default type in custom icon test

tests/large_database_roundtrip_tests.rs
The roundtrip tests can only succeed if the database to be parsed in the
test has been successfully generated at least one time, so tests will
fail when the project was freshly cloned and the tests are run with the
database missing.
Put the whole roundtrip test module behind a feature gate, so that we
test writing and reading at the same time.
=> fix(test): feature-gate roundtrip tests

Cargo.toml, src/config.rs, src/format/kdbx4/dump.rs, src/format/kdbx4/mod.rs, src/xml_db/mod.rs
`getrandom` was renamed to `fill`, [as seen in the CHANGELOG](https://github.com/rust-random/getrandom/blob/master/CHANGELOG.md#breaking-changes)
=> chore: bump getrandom

.github/workflows/ci.yml, .github/workflows/merge.yml, Cargo.toml
I also had to bump the tarpaulin image version since the older cargo version does not support the 2024 edition
=> fix(deps): bump hex-literal

src/config.rs, src/format/kdb.rs, src/format/kdbx3.rs, src/format/kdbx4/dump.rs, src/format/kdbx4/mod.rs, src/format/kdbx4/parse.rs, src/variant_dictionary.rs
Databases created with KeepassXC now contain a KPXC_PUBLIC_UUID field in the public custom data outer header [1], causing parsing to fail because of an unrecognized outer header field. This change adds support for these fields.
[1] https://keepass.info/help/kb/kdbx.html
=> feat(kdbx4): handle public custom data in outer header

src/db/group.rs
BREAKING CHANGE: The `SearchField` enum was removed from the public
interface of the crate, as it is intended for internal use only.
=> fix: do not export internal SearchField enum

src/db/mod.rs, src/format/kdbx4/dump.rs
PR #252 introduced a bug where custom data would get written to the
outer header after it had already ended, leading to the opening of
written databases to fail with a header hash mismatch error. this commit
corrects the order of write operations.
=> fix(kdbx4): writing custom data into outer header

Cargo.toml, src/crypt/kdf.rs
Users can still disable parallelism by setting [the kdf config value](https://github.com/sseemayer/keepass-rs/blob/7f4a27e52a279a1dec0247b4ff1aa2a2f7d0bed6/src/crypt/kdf.rs#L48) to 1, [which will force sequential mode](https://github.com/sru-systems/rust-argon2/commit/d2f26df297e8ad71fc31b47bede67a9a3d7933b4#diff-cba64c21ab992eaad29fce147a08f4560a4769bc14682b8a96081a5fd02dbecdR183).
=> chore: bump rust-argon2

.github/workflows/ci.yml, .github/workflows/merge.yml, flake.nix
Instead of using a docker container with scary options, we can now use tarpaulin via the nix flake. This will ensure that the version of the rust toolchain used when generating the coverage report is the same as the one used both locally and (eventually) in the other CI checks.
This also bumps the version of tarpaulin from 0.32.3 to 0.32.8
=> refactor: use nix to generate coverage report

.github/workflows/ci.yml
I initially wanted to add an `armv8` test job, since GitHub offers `armv8` runners for free for open source projects. I decided to delay this change and for now only consolidate the test jobs into a test matrix since I've waited over 10 minutes for an `armv8` runner to become available :grimacing: 
I added a `Test Suite` rollup step to give us flexibility when adding and removing unit test jobs with different targets or underlying OSes. @sseemayer this means we can remove the `ARMv7 Test Suite` required status check, since this will now be handled by the `Test Suite` rollup step.
We also have a windows job that only builds the project, but I think in a future PR I'm going to add it to the test matrix so that we're also running unit tests on Windows instead of just building the library.
=> ci: consolidate test jobs

.github/workflows/ci.yml, flake.nix
This continues the migration of our CI workflows to using the nix flake, which allows running CI jobs locally, amongst other benefits.
At some point all the jobs will be installing the same nix flake before running their checks, so I'll have to think of a way to cache it first for all the jobs to then use.
=> chore: use nix flake for cargo hack
