- .github/workflows/rust-ci.yml
This adds github workflows. It doesn't delete the travis.yml. It can be amended to do so. Submitted for author feedback.
> Add github workflows

- src/crypt/kdf.rs
Hi!
Currently KDBX3 databases open _very_ slowly,
With this new implementation by @newpavlov ([here](https://github.com/RustCrypto/block-ciphers/issues/285#issuecomment-915097797)) the execution is about ~10x faster
> Faster performance on kdf

- src/config.rs
These consts will also be used when writing databases.
> refactor: extract cipher ids

- README.md
> docs: add a license badge

- src/parse/kdbx4.rs
The `body_start` are parsing artifacts and do not belong in the header. This will become obvious when creating a new database from scratch. This commit removes the `body_start` from the headers and simply returns them from the parsing functions.
> refactor: remove parsing artifact from headers

- src/bin/kp-dump-xml.rs
- src/bin/kp-show-db.rs
- src/parse/kdbx4.rs
This will remove the warnings that are being displayed on every PR.
> chore: fix compilation warnings

- src/parse/kdbx4.rs
Another preliminary PR to https://github.com/sseemayer/keepass-rs/pull/58
Those constants will be used when writing databases as well, so I'm extracting them, along with the comments accompanying them.
> refactor: extract kdbx4 parsing constants

- Cargo.toml
- src/compression.rs
- src/config.rs
- src/crypt/ciphers.rs
- src/crypt/mod.rs
- src/db.rs
- src/hmac_block_stream.rs
- src/lib.rs
- src/parse/kdb.rs
- src/parse/kdbx3.rs
- src/parse/kdbx4.rs
- src/variant_dictionary.rs
- src/xml_parse.rs
This is a first draft for KDBX4 database saving support. This is still a WIP, but I wanted to open the PR now in order to get early feedback. This PR also includes some refactorings that could be extracted to separate PRs in order to make the code review easier and safer.
Fixes https://github.com/sseemayer/keepass-rs/issues/14
> Implement KDBX4 database saving

- src/xml_parse.rs
since we will have to write a lot more of those, let's make it slightly shorter
> chore: reduce verbosity of xml write calls

- src/db.rs
- src/otp.rs
This PR includes several smaller changes to harmonize the OTP codebase with the rest of the crate.
> refactor(totp): cleanup and error handling

- src/db/entry.rs
- src/db/meta.rs
- src/db/mod.rs
- src/parse/kdb.rs
- src/parse/kdbx3.rs
- src/parse/kdbx4.rs
- src/xml_db/dump/entry.rs
- src/xml_db/dump/group.rs
- src/xml_db/dump/meta.rs
- src/xml_db/dump/mod.rs
- src/xml_db/mod.rs
- src/xml_db/parse/meta.rs
- src/xml_db/parse/mod.rs
- tests/file_read_tests.rs
Implement reading and writing of all database metadata.
BREAKING CHANGE: `recyclebin_uuid` is now an `Option<String>`
> feat!: parse and dump all Meta fields

- .github/workflows/rust-ci.yml
- .gitignore
- Cargo.toml
- README.md
- src/bin/kp-get-version.rs
- src/bin/kp-rewrite.rs
- src/config.rs
- src/crypt/ciphers.rs
- src/db/entry.rs
- src/db/mod.rs
- src/hmac_block_stream.rs
- src/parse/kdbx4.rs
- src/parse/mod.rs
- src/variant_dictionary.rs
- src/xml_db/dump/entry.rs
- src/xml_db/dump/meta.rs
- src/xml_db/mod.rs
- src/xml_db/parse/entry.rs
- src/xml_db/parse/mod.rs
> feat!: expose KDBX4 saving behind feature flag

- src/format/kdbx4/mod.rs
See https://github.com/sseemayer/keepass-rs/pull/116#discussion_r1096788388
> chore: use constant for KDBX version

- src/config.rs
- src/format/kdb.rs
- src/format/kdbx3.rs
- src/format/kdbx4/dump.rs
- src/format/kdbx4/parse.rs
See https://github.com/sseemayer/keepass-rs/pull/116#discussion_r1096788746
> refactor: add KDF seed generation to KdfSettings

- .github/workflows/ci.yml
- .github/workflows/merge.yml
This fixes [the following error](https://github.com/sseemayer/keepass-rs/actions/runs/6513961451/job/17694449782?pr=182).
> chore: bump tarpaulin version

- src/format/kdbx4/parse.rs
The goal of this commit is to avoid performing useless work if the header checksum is invalid. I also moved the challenge response closer to the rest of the operations on the DatabaseKey, which I think will help us to extract parts of the DB parsing into smaller functions.
> fix: verify header integrity early when parsing

- src/db/otp.rs
I was implementing a feature to export a KDBX database's TOTP entries to an aegis vault in [keepass-import-export](https://github.com/louib/keepass-import-export) and was unable to access the TOTP fields. I don't think making those fields private improves security, since you can always get the raw otp field from an `Entry` using `get_otp()`. What we might want to do however is to `Zeroize` the `TOTP` struct, to make sure that the secret is cleared from memory after being freed. I opened https://github.com/sseemayer/keepass-rs/issues/203 to track this.
> refactor: make totp fields public

- src/bin/kp-yk-add.rs
- src/bin/kp-yk-recover.rs
- src/bin/kp-yk-remove.rs
This is a continuation of the changes in https://github.com/sseemayer/keepass-rs/pull/207, but for the yubikey utilities merged afterward.
> feat: allow empty passwords for yk utilities

- Cargo.toml
- src/key.rs
The names are still yubikey-centric, but I think that can be addressed in a future PR.
> chore: bump challenge-response

- src/db/otp.rs
> feat: impl Zeroize for TOTP

- src/db/mod.rs
- src/xml_db/dump/mod.rs
Those warnings were raised for example [here](https://github.com/sseemayer/keepass-rs/actions/runs/9142949705/job/25139082283?pr=227#step:4:272)
> chore: fix chrono deprecation warnings

- src/bin/kp-get-version.rs
- src/bin/kp-purge-history.rs
- src/config.rs
- src/crypt/ciphers.rs
- src/db/entry.rs
- src/db/group.rs
- src/db/merge.rs
- src/db/mod.rs
- src/db/node.rs
- src/format/kdb.rs
- src/format/kdbx3.rs
- src/format/kdbx4/dump.rs
- src/format/kdbx4/parse.rs
- src/format/mod.rs
- src/hmac_block_stream.rs
- src/key.rs
- src/variant_dictionary.rs
- src/xml_db/mod.rs
- src/xml_db/parse/entry.rs
- src/xml_db/parse/mod.rs
- tests/entry_tests.rs
Follow the prompts of the `clippy` command and make the following changes.
```bash
cargo clippy --all-features --all-targets -- -D warnings
```
> fix: make clippy happy

- .github/workflows/ci.yml
Fixes https://github.com/sseemayer/keepass-rs/issues/255
> feat: add CI job for building on windows

- .github/CODEOWNERS
Now that @droidmonkey is a collaborator on this repo
> chore: add droidmonkey to codeowners
